import 'dotenv/config';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';
import { Pool } from 'pg';
import { PrismaService } from '../server/prisma/prisma.service.ts';
import { installTestSchema } from './database.ts';

// Real PostgreSQL: exercise migration adoption and the API contracts affected by the ORM.
test('Prisma baseline preserves existing rows; ORM, DTOs, relations, files and transactions', async () => {
  const connectionString = process.env.TEST_DATABASE_URL || process.env.DATABASE_URL;
  assert.ok(connectionString);
  const db = new Pool({connectionString});
  const schema = `sprott_prisma_${randomUUID().replaceAll('-', '')}`;
  const freshSchema = `sprott_prisma_${randomUUID().replaceAll('-', '')}`;
  let app: Awaited<ReturnType<typeof import('../server/main.ts').createApp>> | undefined;
  let prisma: PrismaService | undefined;
  const cli = (...args: string[]) => execFileSync(process.execPath, ['node_modules/prisma/build/index.js', ...args], {env: process.env, stdio: 'pipe'}).toString();
  try {
    await db.query(`CREATE SCHEMA ${schema}`);
    await db.query(`CREATE SCHEMA ${freshSchema}`);
    const url = new URL(connectionString);
    url.searchParams.set('schema', freshSchema);
    process.env.DATABASE_URL = url.toString();
    process.env.NODE_ENV = 'test';
    // Fresh installation and drift check include all foreign keys, defaults and indexes.
    cli('migrate', 'deploy');
    cli('migrate', 'diff', '--from-config-datasource', '--to-schema', 'prisma/schema.prisma', '--exit-code');
    url.searchParams.set('schema', schema);
    process.env.DATABASE_URL = url.toString();
    await installTestSchema(db, schema);
    prisma = new PrismaService();
    const {hash} = await import('../server/common/fields.ts');
    await prisma.user.create({data: {name: 'Admin', email: 'admin@prisma.test', password: hash('Admin-test-123456'), role: 'admin'}});
    const passwordBefore = (await prisma.user.findUniqueOrThrow({where: {id: 1}})).password;
    cli('migrate', 'resolve', '--applied', '0_init');
    cli('migrate', 'deploy');
    cli('migrate', 'deploy');
    assert.equal(await prisma.user.count(), 1);
    assert.equal((await prisma.user.findUniqueOrThrow({where: {id: 1}})).password, passwordBefore);
    const {createApp} = await import('../server/main.ts');
    app = await createApp();
    await app.listen(0, '127.0.0.1');
    const base = `${await app.getUrl()}/api/`;
    let token = '';
    async function request(path: string, method = 'GET', body?: unknown, expected = method === 'POST' ? 201 : 200, bearer = token) {
      const multipart = body instanceof FormData;
      const response = await fetch(base + path, {method, headers: {Authorization: `Bearer ${bearer}`, ...(multipart ? {} : {'Content-Type': 'application/json'})}, body: body === undefined ? undefined : multipart ? body : JSON.stringify(body)});
      const data = await response.json();
      assert.equal(response.status, expected, `${method} ${path}: ${JSON.stringify(data)}`);
      return data;
    }
    const form = (values: Record<string, string>, field?: string, contents = 'binary payload') => {
      const data = new FormData();
      for (const [key, value] of Object.entries(values)) data.set(key, value);
      if (field) data.set(field, new Blob([contents], {type: 'text/plain'}), 'sample.txt');
      return data;
    };
    token = (await request('login', 'POST', {email: 'admin@prisma.test', password: 'Admin-test-123456', role: 'admin'})).token;
    const person = {name: 'Person', surname: 'Test', title: 'Developer', email: 'person@prisma.test', password: 'Person-test-123456'};
    const users = await request('users', 'POST', person);
    const personId = users.find((u: {email: string}) => u.email === person.email).id;
    assert.doesNotMatch(JSON.stringify(users), /password|scrypt/);
    await request('users', 'POST', person, 400);
    await request(`users/${personId}`, 'PATCH', {...person, name: 'Updated'});
    const groupId = (await request('groups', 'POST', {name: 'Team', memberIds: [personId], managerIds: [1]}))[0].id;
    await request('groups', 'POST', {name: 'Team'}, 400);
    await request(`groups/${groupId}`, 'PATCH', {name: 'Should roll back', memberIds: [999999]}, 400);
    assert.equal((await prisma.group.findUniqueOrThrow({where: {id: groupId}})).name, 'Team');
    await request(`permissions/${personId}`, 'PATCH', {permissions: {'task.view': true, 'task.update': true, 'project.view': true, 'forum.view': true}});
    await request(`permissions/${personId}`, 'PATCH', {permissions: {'unknown': true}}, 400);
    const memberToken = (await request('login', 'POST', {email: person.email, password: person.password, role: 'user'}, 201, '')).token;
    const projects = await request('projects', 'POST', {name: 'ORM project', startDate: '2026-01-05', endDate: '2027-01-01'});
    const projectId = projects[0].id;
    await request(`projects/${projectId}/members`, 'POST', {userId: personId});
    await request(`projects/${projectId}/members`, 'POST', {userId: personId});
    await request(`projects/${projectId}`, 'PATCH', {name: 'Updated project', endDate: null});
    await request(`projects/${projectId}`, 'PATCH', {startDate: '2026-02-31'}, 400);
    const board = await request(`projects/${projectId}/board`);
    const [first, second] = board.columns;
    const task = {title: 'ORM task', description: 'Detail', columnId: first.id, assigneeId: personId, dueDate: '2027-01-01'};
    await request('tasks', 'POST', {...task, columnId: true}, 400);
    await request('tasks', 'POST', {...task, priority: 'invalid'}, 400);
    const taskId = (await request('tasks', 'POST', task)).createdTaskId;
    assert.equal((await prisma.task.findUniqueOrThrow({where: {id: taskId}})).dueDate?.toISOString(), '2027-01-01T00:00:00.000Z');
    await request(`tasks/${taskId}`, 'PATCH', {priority: 'highest', dueDate: null});
    const childId = (await request('tasks', 'POST', {...task, title: 'Child', type: 'subtask', parentTaskId: taskId})).createdTaskId;
    await request(`tasks/${taskId}`, 'DELETE', undefined, 400);
    await request(`tasks/${childId}`, 'DELETE');
    await request(`projects/${projectId}/workflow`, 'PUT', {transitions: [{fromColumnId: first.id, toColumnId: second.id}]});
    await request(`tasks/${taskId}`, 'PATCH', {columnId: second.id}, 200, memberToken);
    await request(`tasks/${taskId}`, 'PATCH', {columnId: first.id}, 403, memberToken);
    const attached = await request(`tasks/${taskId}/attachments`, 'POST', form({}, 'files'));
    const attachmentId = attached.tasks[0].attachments[0].id;
    const download = await fetch(`${base}tasks/${taskId}/attachments/${attachmentId}`, {headers: {Authorization: `Bearer ${token}`}});
    assert.equal(download.status, 200); assert.equal(await download.text(), 'binary payload');
    await request(`tasks/${taskId}/attachments/${attachmentId}`, 'PATCH', form({}, 'file', 'replacement'));
    const commented = await request(`tasks/${taskId}/comments`, 'POST', form({body: 'Comment', mentions: JSON.stringify([personId])}, 'files'));
    const comment = commented.tasks[0].comments[0];
    const commentDownload = await fetch(`${base}tasks/${taskId}/comments/${comment.id}/attachments/${comment.attachments[0].id}`, {headers: {Authorization: `Bearer ${token}`}});
    assert.equal(await commentDownload.text(), 'binary payload');
    await request(`tasks/${taskId}/comments/${comment.id}`, 'PATCH', {body: 'Edited', mentions: []});
    const pr = {projectId, title: 'PR', url: 'https://example.test/pr/1', taskIds: [taskId]};
    const prId = (await request('pull-requests', 'POST', pr)).createdPullRequestId;
    await request('pull-requests', 'POST', pr, 400);
    await request(`pull-requests/${prId}`, 'PATCH', {title: 'Updated PR', taskIds: [taskId]});
    await request(`pull-requests/${prId}/state`, 'PATCH', {state: 'merged'});
    for (const route of ['dashboard', 'dashboard/overdue', 'reports', `reports/${personId}`, `logs?projectId=${projectId}`, 'notifications', 'tasks/mine', 'tasks?q=ORM']) await request(route);
    await request('notifications/read', 'PATCH', undefined, 200, memberToken);
    const announcements = await request('announcements', 'POST', form({title: 'Notice', body: 'Content', mandatory: 'true', groupIds: JSON.stringify([groupId])}));
    const announcementId = announcements[0].id;
    await request(`announcements/${announcementId}/read`, 'PATCH', undefined, 200, memberToken);
    assert.ok(await prisma.announcementRead.findUnique({where: {announcementId_userId: {announcementId, userId: personId}}}));
    await request(`announcements/${announcementId}`, 'GET');
    await request(`announcements/${announcementId}`, 'PATCH', form({title: 'No', body: 'No'}), 403);
    const notice = (await request('announcements', 'POST', {title: 'Editable', body: 'Text'}))[0];
    await request(`announcements/${notice.id}`, 'PATCH', {title: 'Changed', body: 'Changed', groupIds: []});
    const forumId = (await request('forums', 'POST', form({name: 'Forum', description: 'Chat'}))).id;
    await request(`forums/${forumId}/members/${personId}`, 'POST');
    const messageId = (await request(`forums/${forumId}/messages`, 'POST', form({body: 'Hello'}, 'files'))).id;
    const messages = await request(`forums/${forumId}/messages`);
    assert.equal(messages[0].body, 'Hello');
    const forumFile = await fetch(`${base}forums/${forumId}/files/${messages[0].files[0].id}`, {headers: {Authorization: `Bearer ${token}`}});
    assert.equal(await forumFile.text(), 'binary payload');
    await request('forums/receipts', 'POST', {ids: [messageId], kind: 'read'}, 201, memberToken);
    await request(`forums/${forumId}/messages/${messageId}/receipts`);
    await request(`forums/${forumId}/messages/${messageId}`, 'PATCH', {body: 'Edited'});
    await request(`forums/${forumId}/messages/${messageId}?scope=me`, 'DELETE', undefined, 200, memberToken);
    await request(`forums/${forumId}/messages/${messageId}?scope=everyone`, 'DELETE');
    assert.equal(await prisma.forumFile.count(), 0);
    await request(`forums/${forumId}`, 'PATCH', form({name: 'Renamed', description: 'Updated'}));
    await request(`projects/${projectId}/completion`, 'PATCH', {completed: true});
    await request(`tasks/${taskId}`, 'PATCH', {title: 'Blocked'}, 403);
    await request(`projects/${projectId}/completion`, 'PATCH', {completed: false});
    await request(`tasks/${taskId}`, 'DELETE');
    assert.equal(await prisma.taskComment.count(), 0);
    assert.equal(await prisma.taskAttachment.count(), 0);
    await request(`pull-requests/${prId}`, 'DELETE');
    await request(`projects/${projectId}`, 'DELETE');
    await request(`forums/${forumId}`, 'DELETE');
    await request(`groups/${groupId}`, 'DELETE');
    await request(`announcements/${announcementId}`, 'DELETE');
    await request(`users/${personId}`, 'DELETE');
    assert.equal(await prisma.user.count(), 1);
  } finally {
    await app?.close();
    await prisma?.$disconnect();
    await db.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);
    await db.query(`DROP SCHEMA IF EXISTS ${freshSchema} CASCADE`);
    await db.end();
  }
});
