ALTER TABLE mcp_tokens ADD COLUMN IF NOT EXISTS id SERIAL UNIQUE;
ALTER TABLE mcp_tokens ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT 'Eski bağlantı';
ALTER TABLE mcp_tokens ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE mcp_tokens ADD COLUMN IF NOT EXISTS "lastUsedAt" TIMESTAMPTZ;
